services:
  picshow:
    image: picshow:latest
    container_name: picshow
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      # Persistant storage of the video
      - /home/slideshow:/home/slideshow
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PI_SLIDESHOW_TITLE="Lobby Display 1"
      - HOME_FOLDER="/home/slideshow"
      - SHOWFILE="video_pi3_photos.mp4"
      
networks: {}
